name: Run test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version:
          - '1.7'
          - '1.6'
          - '1.5'
          - '1.4'
          - '1.3'
          - '1.2'
          - '1.1'
          - '1.0'
          - 'nightly'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: Pkg.test
          name: codecov-umbrella

  # A job that succeeds if and only if all jobs in `test` succeed.
  all-success:
    if: always() && github.event.pull_request
    needs: test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/tkf/merge-conclusions-action
      - uses: tkf/merge-conclusions-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
